[project]
name = "chatagh-rag"
version = "0.1.0"
description = "RAG Chatbot for AGH University of Cracow"
readme = "README.md"
authors = [
  { name="Witold Nowogórski", email="nowogorskiwitold@gmail.com" }
]
[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
langchain = { version = "^0.3.27", python = ">=3.10,<4.0" }
filelock = "3.19.1"
langchain-core = "^0.3.76"
langgraph = "^0.6.7"
dotenv = "^0.9.9"
pymongo = "^4.15.0"
sentence-transformers = "^5.1.0"
langchain-google-genai = "^2.1.10"
rank-bm25 = "^0.2.2"
nltk = "^3.9.1"
scipy = "^1.14.1"

[tool.poetry.group.dev.dependencies]
pandas = "*"
doit = "^0.36.0"
pytest = "^8.4.2"
black = "^25.1.0"
mypy = "^1.18.1"
ruff = "^0.13.0"
coverage = "^7.10.6"
pre-commit = "^3.7.0"
opik = "^1.7.30"

[tool.coverage.run]
branch = true
source = ["src/chat_agh"]

[tool.coverage.report]
show_missing = true

[tool.basedpyright]
reportMissingTypeStubs = "none"

[tool.mypy]
ignore_missing_imports = true
